server:
  port: 8000
spring:
  application:
    name: rabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: host1
    username: admin
    password: admin123
    # 开庆消息确认模式
    # none 无
    # simple 简单模式 简单消息确认
    # correlated
    publisher-confirm-type: simple
    # 开启return监听机制
    publisher-returns: true
